export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_EVENT_TODAY = "GET_EVENT_TODAY";
export const GET_EVENT_UP_COMMING = "GET_EVENT_UP_COMMING";
export const GET_EVENT_BY_TITLE = "GET_EVENT_BY_TITLE";
export const GET_EVENT_BY_CATEGORY = "GET_EVENT_BY_CATEGORY";
export const GET_EVENT_DETAIL = "GET_EVENT_DETAIL";